In [1]:
def remove_dublicates(a):
    for i in range(len(a)):
        for j in range(len(a)):
            if a[i]==a[j] and i!=j:
                print((i+1)*j)
                a[j] = 0
    b = []
    for i in range(len(a)):
        if a[i]!=0:
            b.append(a[i])

    return b

In [2]:
import pandas as pd

In [3]:
f = open("IITB.en-hi.en","r",encoding='utf-8')
lines = f.readlines()
data = []

for line in lines:
    data.append(line)
    
print(len(data))

1659083


In [4]:
df_english = pd.DataFrame(data,columns=['sentences'])

In [5]:
len(df_english)

1659083

In [6]:
df_english.head()

sentences
0  Give your application an accessibility workout\n
1               Accerciser Accessibility Explorer\n
2  The default plugin layout for the bottom panel\n
3     The default plugin layout for the top panel\n
4  A list of plugins that are disabled by default\n

In [7]:
df_english['sentences'] = df_english['sentences'].apply(lambda x: x[:-1])

In [8]:
df_english

sentences
0           Give your application an accessibility workout
1                        Accerciser Accessibility Explorer
2           The default plugin layout for the bottom panel
3              The default plugin layout for the top panel
4           A list of plugins that are disabled by default
...                                                    ...
1659078  The Prime Minister, Shri Narendra Modi has con...
1659079  In a tweet, the Prime Minister said, congratul...
1659080  I also congratulate all those who took oath as...
1659081  The NDA family will work together for the prog...
1659082  I assure all possible support from the Centre ...

[1659083 rows x 1 columns]

In [9]:
df_english['flag'] = df_english['sentences'].apply(lambda x: 'True' if type(x)==type(df_english['sentences'][0]) and len(x)>30 and len(x)<90 else 'False')
flag = df_english['flag']
df_english.head(12)

sentences   flag
0      Give your application an accessibility workout   True
1                   Accerciser Accessibility Explorer   True
2      The default plugin layout for the bottom panel   True
3         The default plugin layout for the top panel   True
4      A list of plugins that are disabled by default   True
5                                  Highlight duration  False
6   The duration of the highlight box when selecti...   True
7                              Highlight border color  False
8      The color and opacity of the highlight border.   True
9                                Highlight fill color  False
10       The color and opacity of the highlight fill.   True
11                                        API Browser  False

In [10]:
f = open("IITB.en-hi.hi","r",encoding='utf-8')
lines = f.readlines()
data = []
string = '' 
for line in lines:
    data.append(line[:-1])

In [11]:
data = list(zip(data, flag))
df_hindi = pd.DataFrame(data,columns=['sentences','flag'])

In [12]:
error = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
         'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '(', ')' ]
special_char=['/','.','¨','¾','®','¥','à','¤','©','+','=','%','@','#','$','`','~','-','1','2','3','4','5','6','7','8','9','0']

error=error+special_char

string = df_hindi['sentences'][45534]
string1 ='दायाँ स्थिति इंच अक्षर'
string2 = 'GL पिक्सेल उद्धरण ऑब्जेक्ट के प्रयोग को अक्षम करें'
def check1(x):
    for k in error:
        try: 
            x.index(k.upper())
            return False
        except ValueError as v:
            pass
        
    return True

def check2(x):
    for k in error:
        try: 
            x.index(k.lower())
            return False
        except ValueError as v:
            pass
        
    return True

print(string)
print(not check1(string) or not check2(string))
print(not check1(string1) or not check2(string1))
print(not check1(string2) or not check2(string2))
df_hindi['flag1'] = df_hindi['sentences'].apply(lambda x: 'False' if (not check1(x)  or not check2(x)) else 'True')

GL पिक्सेल उद्धरण ऑब्जेक्ट के प्रयोग को अक्षम करें
True
False
True


In [13]:
df_hindi['flag2'] = df_hindi['sentences'].apply(lambda x: 'True' if len(x)<90 else 'False')

In [14]:
flag1 = df_hindi['flag1']
flag2 = df_hindi['flag2']
df_hindi = df_hindi[df_hindi['flag'] == 'True']
df_hindi = df_hindi[df_hindi['flag1'] == 'True']
df_hindi = df_hindi[df_hindi['flag2'] == 'True']
df_hindi = pd.DataFrame(df_hindi['sentences'][:300000])
df_hindi = df_hindi.reset_index(drop = True)



df_english['flag1'] = flag1
df_english['flag2'] = flag2
df_english = df_english[df_english['flag'] == 'True']
df_english = df_english[df_english['flag1'] == 'True']
df_english = df_english[df_english['flag2'] == 'True']
df_english = pd.DataFrame(df_english['sentences'][:300000])
df_english = df_english.reset_index(drop=True)

In [15]:
print(df_hindi.head(1))
print(df_english.head(1))

                                         sentences
0  अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें
                                        sentences
0  Give your application an accessibility workout


In [16]:
print(len(df_hindi), len(df_english))

300000 300000


In [17]:
Hindi = [f'[start] {sentence} [end]' for sentence in df_hindi['sentences']] 
English = [sentence for sentence in df_english['sentences']]

In [18]:
text_pairs = []

for i in range(len(Hindi)):
    text_pairs.append([English[i], Hindi[i]])

In [19]:
import random
for i in range(3):
    print(random.choice(text_pairs))

['He devoted much of his energy to the betterment of the people.', '[start] उसने अपनी शक्ति का अधिकांश भाग लोगों के जीवन को बेहतर बनाने में लगाया।  [end]']
['We must take destiny in our own hands to build the Indiaof our dreams.', '[start] हमें अपने सपनों के भारत का निर्माण करने के लिए भाग्य को अपनी मुट्ठी में करना होगा। [end]']
['Presently four oil refineries have been working in the State including the one at Digboi.', '[start] इस समय राज्य में चार तेलशोधक कारखाने काम कर रहे हैं, जिनमें से एक डिगबोई में है।  [end]']


In [20]:
max1 = 0
max2 = 0
index1 = 0
index2 = 0
for i in range(len(text_pairs)):
    if len(text_pairs[i][1])>max2:
        max2 = len(Hindi[i])
        index2 = i
    if len(text_pairs[i][0])>max1:
        max1 = len(English[i])
        index1 = i
        
print(index1, index2)

14562 14793


In [21]:
random.shuffle(text_pairs)
length = len(text_pairs)
len_val_samples = int(0.01 * length)

In [22]:
len_train_samples = length - 2*len_val_samples

train_pairs = text_pairs[:len_train_samples]
val_pairs = text_pairs[len_train_samples:len_train_samples+len_val_samples]
test_pairs = text_pairs[len_train_samples+len_val_samples:]

In [1]:
import tensorflow as tf
import tensorflow.keras.layers as layers
import tensorflow.keras as keras
import re
import string

strip_chars = string.punctuation
strip_chars = strip_chars.replace('[', '')
strip_chars = strip_chars.replace(']', '')

In [24]:
def custom_standardization(input_string):
    lowercase = tf.strings.lower(input_string)
    return tf.strings.regex_replace(
        lowercase, f"[{re.escape(strip_chars)}]", "")

vocab_size = 50000
sequence_length = 20

source_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length,
    
)
target_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length + 1,
    standardize=custom_standardization,
)
train_english_texts = [pair[0] for pair in train_pairs]
train_hindi_texts = [pair[1] for pair in train_pairs]
source_vectorization.adapt(train_english_texts)
target_vectorization.adapt(train_hindi_texts)

In [25]:
print(tf.__version__)

2.10.1


In [26]:
batch_size = 64

def format_dataset(eng, hin):
    eng = source_vectorization(eng)
    hin = target_vectorization(hin)
    return ({
        "english": eng,
        "hindi": hin[:, :-1],
    }, hin[:, 1:])

def make_dataset(pairs):
    eng_texts, hin_texts = zip(*pairs)
    eng_texts = list(eng_texts)
    hin_texts = list(hin_texts)
    dataset = tf.data.Dataset.from_tensor_slices((eng_texts, hin_texts))
    dataset = dataset.batch(batch_size)
    dataset = dataset.map(format_dataset, num_parallel_calls=4)
    return dataset.shuffle(2048).prefetch(16).cache()

train_ds = make_dataset(train_pairs)
val_ds = make_dataset(val_pairs)

In [27]:
for inputs, targets in train_ds.take(1):
    print(f"inputs['english'].shape: {inputs['english'].shape}")
    print(f"inputs['hindi'].shape: {inputs['hindi'].shape}")
    print(f"targets.shape: {targets.shape}")
    print(inputs["hindi"])
    print(targets)

inputs['english'].shape: (64, 20)
inputs['hindi'].shape: (64, 20)
targets.shape: (64, 20)
tf.Tensor(
[[    2    42    35 ...     0     0     0]
 [    2  4333 10415 ...     0     0     0]
 [    2  4775     6 ...     0     0     0]
 ...
 [    2 31208    11 ...     0     0     0]
 [    2    13  3008 ...     0     0     0]
 [    2  9149 11329 ...     0     0     0]], shape=(64, 20), dtype=int64)
tf.Tensor(
[[   42    35   384 ...     0     0     0]
 [ 4333 10415     4 ...     0     0     0]
 [ 4775     6   402 ...     0     0     0]
 ...
 [31208    11  7499 ...     0     0     0]
 [   13  3008  2368 ...     0     0     0]
 [ 9149 11329    10 ...     0     0     0]], shape=(64, 20), dtype=int64)


In [28]:
class TransformerEncoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()

    def call(self, inputs, mask=None):
        if mask is not None:
            mask = mask[:, tf.newaxis, :]
        attention_output = self.attention(
            inputs, inputs, attention_mask=mask)
        proj_input = self.layernorm_1(inputs + attention_output)
        proj_output = self.dense_proj(proj_input)
        return self.layernorm_2(proj_input + proj_output)

    def get_config(self):
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "dense_dim": self.dense_dim,
        })
        return config

In [29]:
class TransformerDecoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention_1 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.attention_2 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()
        self.layernorm_3 = layers.LayerNormalization()
        self.supports_masking = True

    def get_config(self):
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "dense_dim": self.dense_dim,
        })
        return config

    def get_causal_attention_mask(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size, sequence_length = input_shape[0], input_shape[1]
        i = tf.range(sequence_length)[:, tf.newaxis]
        j = tf.range(sequence_length)
        mask = tf.cast(i >= j, dtype="int32")
        mask = tf.reshape(mask, (1, input_shape[1], input_shape[1]))
        mult = tf.concat(
            [tf.expand_dims(batch_size, -1),
             tf.constant([1, 1], dtype=tf.int32)], axis=0)
        return tf.tile(mask, mult)

    def call(self, inputs, encoder_outputs, mask=None):
        causal_mask = self.get_causal_attention_mask(inputs)
        if mask is not None:
            padding_mask = tf.cast(
                mask[:, tf.newaxis, :], dtype="int32")
            padding_mask = tf.minimum(padding_mask, causal_mask)
        attention_output_1 = self.attention_1(
            query=inputs,
            value=inputs,
            key=inputs,
            attention_mask=causal_mask)
        attention_output_1 = self.layernorm_1(inputs + attention_output_1)
        attention_output_2 = self.attention_2(
            query=attention_output_1,
            value=encoder_outputs,
            key=encoder_outputs,
            attention_mask=padding_mask,
        )
        attention_output_2 = self.layernorm_2(
            attention_output_1 + attention_output_2)
        proj_output = self.dense_proj(attention_output_2)
        return self.layernorm_3(attention_output_2 + proj_output)

In [30]:
seqclass PositionalEmbedding(layers.Layer):
    def __init__(self, sequence_length, input_dim, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.token_embeddings = layers.Embedding(
            input_dim=input_dim, output_dim=output_dim)
        self.position_embeddings = layers.Embedding(
            input_dim=sequence_length, output_dim=output_dim)
        self.sequence_length = sequence_length
        self.input_dim = input_dim
        self.output_dim = output_dim

    def call(self, inputs):
        length = tf.shaseqpe(inputs)[-1]
        positions = tf.range(start=0, limit=length, delta=1)
        embedded_tokens = self.token_embeddings(inputs)
        embedded_positions = self.position_embeddings(positions)
        return embedded_tokens + embedded_positions

    def compute_mask(self, inputs, mask=None):
        return tf.math.not_equal(inputs, 0)

    def get_config(self):
        config = super(PositionalEmbedding, self).get_config()
        config.update({
            "output_dim": self.output_dim,
            "sequence_length": self.sequence_length,
            "input_dim": self.input_dim,
        })
        return config

In [31]:
embed_dim = 256
dense_dim = 2048
num_heads = 8

encoder_inputs = keras.Input(shape=(None,), dtype="int64", name="english")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(encoder_inputs)
encoder_outputs = TransformerEncoder(embed_dim, dense_dim, num_heads)(x)

decoder_inputs = keras.Input(shape=(None,), dtype="int64", name="hindi")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(decoder_inputs)
x = TransformerDecoder(embed_dim, dense_dim, num_heads)(x, encoder_outputs)
x = layers.Dropout(0.5)(x)
decoder_outputs = layers.Dense(vocab_size, activation="softmax")(x)
transformer = keras.Model([encoder_inputs, decoder_inputs], decoder_outputs)

In [32]:
transformer.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 english (InputLayer)           [(None, None)]       0           []                               
                                                                                                  
 hindi (InputLayer)             [(None, None)]       0           []                               
                                                                                                  
 positional_embedding (Position  (None, None, 256)   12805120    ['english[0][0]']                
 alEmbedding)                                                                                     
                                                                                                  
 positional_embedding_1 (Positi  (None, None, 256)   12805120    ['hindi[0][0]']              

In [33]:
transformer.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])
transformer.fit(train_ds, epochs=15)

Epoch 1/15
3282/3282 [==============================] - 470s 142ms/step - loss: 2.9794 - accuracy: 0.3108
Epoch 2/15
3282/3282 [==============================] - 487s 148ms/step - loss: 2.3231 - accuracy: 0.4075
Epoch 3/15
3282/3282 [==============================] - 481s 147ms/step - loss: 2.0085 - accuracy: 0.4633
Epoch 4/15
3282/3282 [==============================] - 506s 154ms/step - loss: 1.8002 - accuracy: 0.5022
Epoch 5/15
3282/3282 [==============================] - 513s 156ms/step - loss: 1.6467 - accuracy: 0.5323
Epoch 6/15
3282/3282 [==============================] - 512s 156ms/step - loss: 1.5235 - accuracy: 0.5573
Epoch 7/15
3282/3282 [==============================] - 509s 155ms/step - loss: 1.4227 - accuracy: 0.5780
Epoch 8/15
3282/3282 [==============================] - 508s 155ms/step - loss: 1.3387 - accuracy: 0.5957
Epoch 9/15
3282/3282 [==============================] - 507s 154ms/step - loss: 1.2657 - accuracy: 0.6124
Epoch 10/15
3282/3282 [=======================

In [38]:
transformer.evaluate(val_ds)

704/704 [==============================] - 58s 82ms/step - loss: 2.1014 - accuracy: 0.5090


[2.1013667583465576, 0.509003758430481]

In [39]:
tf.keras.models.save_model(
    transformer,
    './save',
    overwrite=True,
    include_optimizer=True,
    save_format=None,
    signatures=None,
    options=None,
    save_traces=True
)

INFO:tensorflow:Assets written to: ./save\assets


INFO:tensorflow:Assets written to: ./save\assets


In [2]:
trans = tf.saved_model.load('./save/')

In [70]:
file = open("sou.csv", "w")
 
str = repr(source_vectorization.get_vocabulary())
file.write(str)

file.close()


file = open("tar.csv", "w")
 
str = repr(target_vectorization.get_vocabulary())
file.write(str)

file.close()

In [58]:
import pandas as pd
import numpy as np

source_vocab = pd.read_csv('source.csv', header=None)
source_vocab = np.array(source_vocab)
source_vocab = source_vocab[0]

for i in range(len(source_vocab)):
    source_vocab[i] = source_vocab[i][2:-1]
    

target_vocab = pd.read_csv('target.csv', header=None)
target_vocab = np.array(target_vocab)
target_vocab = target_vocab[0]

for i in range(len(source_vocab)):
    target_vocab[i] = target_vocab[i][2:-1]
target_vocab[-1] = target_vocab[-1][:-1]

In [61]:
vocab_size = 50000
sequence_length = 20

def custom_standardization(input_string):
    lowercase = tf.strings.lower(input_string)
    return tf.strings.regex_replace(
        lowercase, f"[{re.escape(strip_chars)}]", "")

target = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length + 1,
    standardize=custom_standardization,
)

target.set_vocabulary(target_vocab)

source = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length,
)

source.set_vocabulary(source_vocab)

In [69]:
import numpy as np
hin_vocab = target.get_vocabulary()
hin_index_lookup = dict(zip(range(len(hin_vocab)), hin_vocab))
max_decoded_sentence_length = 20

def decode_sequence(input_sentence):
    tokenized_input_sentence = source([input_sentence])
    decoded_sentence = "[start]"
    for i in range(max_decoded_sentence_length):
        tokenized_target_sentence = target([decoded_sentence])[:, :-1]
        predictions = trans([tokenized_input_sentence, tokenized_target_sentence])
        sampled_token_index = np.argmax(predictions[0, i, :])
        sampled_token = hin_index_lookup[sampled_token_index]
        decoded_sentence += " " + sampled_token
        if sampled_token == "[end]":
            break
    return decoded_sentence

# test_eng_texts = [pair[0] for pair in test_pairs]
# for _ in range(80,100):
#     input_sentence = random.choice(test_eng_texts)
#     print("-")
#     print(input_sentence)
#     print(decode_sequence(input_sentence))
    
input_sentence = ['Manage finances']
print("-")
print(input_sentence)
print(decode_sequence(input_sentence))

-
['Manage finances']
[start] वित्तीय सेवा प्रबंधन [end]
